### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by fynn1307** [Sheharyar566/inspire_me#1]
Hello, can you help me with a custom api?
Best regards!

**Comment by Sheharyar566** [comment]
Hi there fynn

can you please explain what sort of api are we talking about?

Regards

**Comment by fynn1307** [comment]
Hi, thanks for your answer. 
I found an Api on your website (Taxipro) which calculates the estimated price.
Can we discuss about email? I send you an email. Best Regards!

**Comment by Sheharyar566** [comment]
Hi there fynn,

Sorry i am not sure which api you are referring to. Cause I dont have a
website by the name of Taxipro.

Regrads

**Comment by fynn1307** [comment]
Sorry, I mean: taxis.plus.
You posted a screenshot on other Github-Project.

**Comment by Sheharyar566** [comment]
hi there fynn,

Can you please tell me how you know about me working on taxis.plus?

Regards

**Comment by fynn1307** [comment]
Hello, I want to build the Form with Calculation on https://taxis.plus/.
Can you help me to set up an Api for Fare calculation? Please connect via email.
I already send you an Mail. Regards and thanks for your help!

**Comment by Sheharyar566** [comment]
Sorry fynn... that will be pretty difficult... for two reasons

1. I am a front end guy (I can do it tho)....
2. The fare calculation is a pretty difficult task due to the number of tasks involved

**Comment by fynn1307** [comment]
Is it possible that you share the code privat?

**Comment by Sheharyar566** [comment]
sorry cant do that....

**Comment by fynn1307** [comment]
And can you share some information about it? Which library are u uisng? Can you give me contact details from developer made it? I realy need it... but cant find any infomation in the internet

**Comment by fynn1307** [comment]
do you have some information how you created it?

**Comment by Sheharyar566** [comment]
Sorry cant do that either...
